project:
  type: website
  output-dir: docs

website:
  title: "Tyler Lowry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - posts.qmd
    right:
      - icon: github
        href: https://github.com/tjlowry
      - icon: linkedin
        href: www.linkedin.com/in/tylerj-lowry

format:
  html:
    theme: lux
    css: styles.css
    toc: true



